---
title: "Prediction for presentation"
author: "Zhang"
date: "2025-04-14"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


----------

This code contains 1) Data analysis and the figures for the presentation, shown in `# Preparation` chunk. 2) Predictions without using any variables, shown in `# Predictions`

Models contains:
- Neural Network
- State Space - smooth
- State Space - BSM

You may also open the outline of this document, it is more clear for you to get the structure of the code.

----------





```{r chunks, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r libraries, include=FALSE}
#retrieve libraries
library(here)
library(ggplot2)
library(forecast)
library(cowplot)
library(Kendall)
library(tseries)
library(kableExtra)
library(dplyr)
library(smooth)

set.seed(797)

```


# Preparation

```{r include=FALSE}
#upload test and training data
methane_train <- read.csv("../Data/Processed/methane_training.csv")
methane_test <- read.csv("../Data/Processed/methane_test.csv")
methane_all <- read.csv("../Data/Processed/methane_all.csv")

#create ts object
methane_train_ts <-ts(methane_train$average, 
                start = c(1983,7), 
                end = c(2021, 12), 
                frequency = 12)

methane_test_ts <-ts(methane_test$average, 
                start = c(2022,1), 
                end = c(2024, 12), 
                frequency = 12)

#create msts
methane_train_msts <- msts(methane_train$average, 
                            seasonal.periods =c(4,12),
                            start=c(1983,7)) 

methane_test_msts <- msts(methane_test$average, 
                            seasonal.periods =c(4,12),
                            start=c(2022,1))
```


# Relationship between external variables
```{r}

social_economic <- read.csv("../Data/Processed/social_economic_factors_monthly.csv")
beef_production <- read.csv("../Data/Processed/beef_production.csv") 

```

## Drawing for beef production

```{r warning = FALSE}

methane_yearly <- read.csv("../Data/Processed/social_economic_factors_yearly.csv") 

methane_yearly <- methane_all %>% 
  filter(year <= 2021) %>% 
  group_by(year) %>% 
  summarize(yearly_average = mean(average))

methane_yearly <- cbind(methane_yearly, beef_production %>% filter(Year <= 2021))

p <- ggplot(methane_yearly, mapping = aes(x = log(Beef_Production.Tons.), y = yearly_average)) + geom_point() + geom_smooth(method="lm") 

p + geom_point()+
  theme(panel.grid = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12)
        )+
  ylab("Yearly Methane Emission")+
  xlab("log(Beef Production)")

ggsave("../Figures/Presentation/beef_relationship.svg",
       width = 5,
       height = 5,
       dpi = 100)

```

## Drawing for social economic factors

```{r warning = FALSE}
social_economic_panel <- read.csv("../Data/Processed/social_economic_factors_monthly_paneldata.csv")

social_economic_panel$social.factors <- factor(
  social_economic_panel$social.factors,
  levels = c("cpi", "export", "import", "ip"),
  labels = c("Consumer Price Index", "Merchandise Exports", "Merchandise Imports", "Industrial Production")
)


p2 <- ggplot(social_economic_panel, mapping = aes(x = value, y = methane)) 

p2 + geom_point(size = 0.3) + facet_wrap(~ social.factors, nrow = 2) + geom_smooth(method="lm") +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12)
        )+
  ylab("Monthly Methane Emission")+
  xlab("Social Economic Factors")

ggsave("../Figures/Presentation/social_relationship.svg",
       width = 5,
       height = 5,
       dpi = 100)


```

```{r warning = FALSE}
library(corrplot)


social_data_monthly <- read.csv("../Data/Processed/social_economic_factors_monthly.csv")

corr_data <- cor(social_data_monthly)

colnames(corr_data) <- c("Methane Production","Consumer Price Index", "Merchandise Exports", "Merchandise Imports", "Industrial Production")
rownames(corr_data) <- c("Methane Production","Consumer Price Index", "Merchandise Exports", "Merchandise Imports", "Industrial Production")


svg("../Figures/Presentation/correlation matrix.svg", width = 8, height = 8)

corrplot(corr_data,
         tl.col = "black",
         method = "color",
         addCoef.col = "white",
         type = "upper",
         tl.srt = 30)

dev.off()

```



# Predictions

## Neural Network

```{r}

NN_fit <- nnetar(methane_train_ts, p = 1, P = 7)

NN_for <- forecast(NN_fit, h=36)

forecast_NN_accuracy <- accuracy(NN_for$mean, methane_test_ts)

print(forecast_NN_accuracy)

plot(NN_for)

```

```{r}

NN_fourier_fit <- nnetar(methane_train_msts, p = 0, P = 7,
                 xreg=fourier(methane_train_msts,K=c(2,6)))

NN_fourier_for <- forecast(NN_fourier_fit, h=36, xreg=fourier(methane_train_msts,K=c(2,6), h=36))

forecast_NN_fourier_accuracy <- accuracy(NN_fourier_for$mean, methane_test_msts)

print(forecast_NN_fourier_accuracy)

plot(NN_fourier_for)

```

## State Space - Smooth

```{r}

SSES <- es(methane_train_ts,model="ZZZ",h=36,holdout=FALSE)

SSES_for <-forecast(SSES,h=36, interval="prediction")

plot(SSES_for)

forecast_SSES_accuracy <- accuracy(SSES$forecast, methane_test_ts)

print(forecast_SSES_accuracy)

```

## State Space - BSM

```{r}

SSBSM <- StructTS(methane_train_ts,
                    type="BSM",fixed=c(NA,NA,NA,NA))

SSBSM_for <- forecast(SSBSM,h=36)

plot(SSBSM_for)

forecast_SSBSM_accuracy <- accuracy(SSBSM_for$mean,methane_test_ts)

print(forecast_SSBSM_accuracy)

```




# Performance Comparison

```{r echo=FALSE}
# Combine performance vectors as rows
forecast_performance <- data.frame(rbind(forecast_NN_accuracy, 
                                         forecast_NN_fourier_accuracy,
                                         forecast_SSES_accuracy,
                                         forecast_SSBSM_accuracy))

# Set row names
rownames(forecast_performance) <- c("Neural Network",
                                    "Neural Network w/fourier",
                                    "State Space w/Exponential smoothing",
                                    "State Space w/BSM")
```

```{r}
kable(forecast_performance,
      #format = "latex",  # Works for PDF output
      caption = "Forecast Accuracy",
      digits = 3,
      booktabs = TRUE)

```

```{r}

temperature <- read.csv("../Data/Raw/temperature_anomaly.csv", skip = 4)
temperature$Year <- as.integer(substr(temperature$Date, 1, 4))
temperature$Month <- as.integer(substr(temperature$Date, 5, 6))

temperature <- temperature %>%
  filter(
    (Year > 1983 | (Year == 1983 & Month >= 7)) &
    (Year < 2025 | (Year == 2024 & Month < 11))
  ) %>% filter(Year == 2024 & Month == 12)

combined <- cbind(temperature, methane_all)

combined$yearmonth <- as.Date(paste0(combined$Year, "-", combined$Month, "-01"))


```

```{r}

p <- ggplot(combined, mapping = aes(x = yearmonth)) +
  geom_line(aes(y = Anomaly), color = "blue") +
  geom_line(aes(y = average), color = "red")

p

```







# A tool to find the optimal parameter

## Find the optimal parameter for NN

```{r eval = FALSE}
# i and j in the loop are the parameter for p and P. Basically it could output the model performance iteratively, then you could choose the parameter with the best performance. 

for (i in 0:3){
    for (j in 0:8){
      
      if (i == 0 & j == 0){
        next
      }
      
      NN_fit <- nnetar(methane_train_ts, p = i, P = j)
      
      NN_for <- forecast(NN_fit, h=36)
      
      forecast_NN_accuracy <- accuracy(NN_for$mean, methane_test_ts)
      
      
      cat("p=",i,"P=",j,"\n")
      print(forecast_NN_accuracy)
      
      
    }
}


```

## Find the optimal parameter for NN w/fourier

```{r eval = FALSE}

for (i in 0:2){
    for (j in 0:8){
      
      if (i == 0 & j == 0){
        next
      }
      
      NN_fourier_fit <- nnetar(methane_train_msts, p = i, P = j,
                 xreg=fourier(methane_train_msts,K=c(2,6)))

      NN_fourier_for <- forecast(NN_fourier_fit, h=36, xreg=fourier(methane_train_msts,K=c(2,6), h=36))

      forecast_NN_fourier_accuracy <- accuracy(NN_fourier_for$mean, methane_test_msts)
      
      cat("p=",i,"P=",j,"\n")
      print(forecast_NN_fourier_accuracy)
      
    }
}

  


```



