---
title: "Forecast_w_social_predictor_John"
author: "Zhang"
date: "2025-04-20"
output: pdf_document
---


```{r chunks, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r libraries, include=FALSE}
#retrieve libraries
library(here)
library(ggplot2)
library(forecast)
library(cowplot)
library(Kendall)
library(tseries)
library(kableExtra)
library(dplyr)
library(smooth)

set.seed(797)

```



# Preparation: Import and split data to training and test sets

```{r include=FALSE}
# Import social economic factors with methane
methane_all <- read.csv("../Data/Processed/social_economic_factors_monthly.csv")


# Transform to time series
methane_all_ts <- ts(methane_all, 
                start = c(1983,7), 
                end = c(2024,11),
                frequency = 12)

methane_all_msts <- msts(methane_all, 
                            seasonal.periods =c(4,12),
                            start = c(1983,7),
                            end = c(2024,11))


# Split to training and test sets
methane_train_ts <- window(methane_all_ts, end=c(2021,12))
methane_test_ts <- window(methane_all_ts, start=c(2022,1))

methane_train_msts <- window(methane_all_msts, end=c(2021,12))
methane_test_msts <- window(methane_all_msts, start=c(2022,1))



```


# Predictions

## Neuron Network

### Choose the best variable combination
```{r include=FALSE}

variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

for(variable in variables){
  
  NN_fit <- nnetar(methane_train_ts[,1], xreg = methane_train_ts[,variable], p = 0, P = 7, repeats = 50)

  NN_for <- forecast(NN_fit, xreg = methane_test_ts[,variable], h=36)
  
  forecast_NN_accuracy <- accuracy(NN_for$mean, methane_test_ts[,1])
  
  cat(variable,":\n")
  
  print(forecast_NN_accuracy)
}



```

# Best model of Neural Network

```{r}

NN_fit <- nnetar(methane_train_ts[,1], xreg = methane_train_ts[,c(2,3,4)], p = 0, P = 7)

NN_for <- forecast(NN_fit, xreg = methane_test_ts[,c(2,3,4)], h=35)

forecast_NN_accuracy <- accuracy(NN_for$mean, methane_test_ts[,1])

print(forecast_NN_accuracy)

plot(NN_for)

```



### Choose the best variable combination

```{r echo=FALSE}

variables <- list(c(2),c(3),c(4),c(5))

for(variable in variables){
  
  #autofit the sarima model
arima_autofit <- auto.arima(methane_train_ts[,1], 
                            max.D = 0, 
                            max.P = 0, 
                            max.Q = 0,
                            xreg = methane_train_ts[,variable])


#create the sarima forecast with the autofit
forecast_arima <- forecast(object = arima_autofit, h = 35,xreg = methane_test_ts[,variable])

#calculate accuracy metrics
forecast_arima_accuracy <- accuracy(forecast_arima$mean, methane_test_ts[,1])
  
  cat(variable,":\n")
  
  print(forecast_arima_accuracy)


}

```
Best model:
- Factor: Number 5 (ip)

## Best model of Arima

```{r echo=FALSE}
#autofit the sarima model
arima_autofit <- auto.arima(methane_train_ts[,1], 
                            max.D = 0, 
                            max.P = 0, 
                            max.Q = 0,
                            xreg = methane_train_ts[,5])
print(arima_autofit)

#get residuals
#checkresiduals(arima_autofit)

#create the sarima forecast with the autofit
forecast_arima <- forecast(object = arima_autofit, h = 35,xreg = methane_test_ts[,5])

#calculate accuracy metrics
forecast_arima_accuracy <- accuracy(forecast_arima$mean, methane_test_ts[,1])

print(forecast_arima_accuracy)

#plot the forecast
plot(forecast_arima)
```


## SARIMA

```{r echo=FALSE}
#autofit the sarima model
sarima_autofit <- auto.arima(methane_train_ts[,1],xreg = methane_train_ts[,5])
print(sarima_autofit)

#get residuals
checkresiduals(sarima_autofit)

#create the sarima forecast with the autofit
forecast_sarima <- forecast(object = sarima_autofit, h = 35,xreg = methane_test_ts[,5])

#calculate accuracy metrics
forecast_sarima_accuracy <- accuracy(forecast_sarima$mean, methane_test_ts[,1])

#plot the forecast
plot(forecast_sarima)
```

```{r}

#variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

variables <- list(c(2),c(3),c(4),c(5))

for(variable in variables){

sarima_autofit <- auto.arima(methane_train_ts[,1],xreg = methane_train_ts[,variable])
print(sarima_autofit)

#get residuals
checkresiduals(sarima_autofit)

#create the sarima forecast with the autofit
forecast_sarima <- forecast(object = sarima_autofit, h = 35,xreg = methane_test_ts[,variable])

#calculate accuracy metrics
forecast_sarima_accuracy <- accuracy(forecast_sarima$mean, methane_test_ts[,1])



  cat(variable,":\n")
  
  print(forecast_sarima_accuracy)
}


```


## TBATS 

```{r}

#variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

variables <- list(c(2),c(3),c(4),c(5))

result <- list()

for(variable in variables){

 #fit TBATS
tbats_fit <- tbats(methane_train_msts[,1],xreg = methane_train_msts[,variable])

#forecasting test data
tbats_forecast <- forecast(tbats_fit, h = length(methane_test_msts[,1]),xreg = methane_test_msts[,variable])

#accuracy assessment
tbats_accuracy <- accuracy(tbats_forecast$mean, methane_test_msts[,1]) 
  


  
  result_list <- data.frame(Variable_colnum = variable, RMSE = tbats_accuracy[,"MAPE"])
  
  result <- append(result,list(result_list))
  
  cat(variable,":\n")
  
  print(tbats_accuracy)

}

rmse_values <- sapply(result, function(x) x$RMSE)

best_index <- which.min(rmse_values)

best_result <- result[[best_index]]

print(best_result)

```


```{r}
#fit TBATS
tbats_fit <- tbats(methane_train_msts[,1],xreg = methane_train_msts[,2])

#forecasting test data
tbats_forecast <- forecast(tbats_fit, h = length(methane_test_msts[,1]),xreg = methane_test_msts[,2])

#accuracy assessment
tbats_accuracy <- accuracy(tbats_forecast$mean, methane_test_msts[,1])

#visualization
plot(tbats_forecast)

print(tbats_accuracy)



```

## STL+arima   (Note: STL only supports arima model for external variables)


```{r}

#variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

variables <- list(c(2),c(3),c(4),c(5))

result <- list()

for(variable in variables){

stl_arima_fit <- stlm(methane_train_ts[,1], xreg = methane_train_ts[,variable], s.window = "periodic", method = "arima")

#forecasting test data
stl_arima_forecast <- forecast(stl_ets_fit, h = length(methane_test_ts), xreg = methane_test_ts[,variable])

#accuracy assessment
stl_arima_accuracy <- accuracy(stl_arima_forecast$mean, methane_test_ts[,1])
  

  cat(variable,":\n")
  
  print(stl_arima_accuracy)
  
  #####
  # Find the best variable
  #####
  
  result_list <- data.frame(Variable_colnum = variable, RMSE = stl_arima_accuracy[,"MAPE"])
  
  result <- append(result,list(result_list))
  
 

}

rmse_values <- sapply(result, function(x) x$RMSE)

best_index <- which.min(rmse_values)

best_result <- result[[best_index]]

print("The best combination is: \n")
print(best_result)

```






```{r}
#fit STL with ETS
stl_arima_fit <- stlm(methane_train_ts[,1], xreg = methane_train_ts[,2], s.window = "periodic", method = "arima")

#forecasting test data
stl_arima_forecast <- forecast(stl_ets_fit, h = length(methane_test_ts), xreg = methane_test_ts[,2])

#accuracy assessment
stl_arima_accuracy <- accuracy(stl_ets_forecast$mean, methane_test_ts[,1])

#visualization
plot(stl_arima_forecast)

print(stl_arima_accuracy)

```

## State Space

```{r}

variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

#variables <- list(c(2),c(3),c(4),c(5))

result <- list()

for(variable in variables){

stl_arima_fit <- stlm(methane_train_ts[,1], xreg = methane_train_ts[,variable], s.window = "periodic", method = "arima")

#forecasting test data
stl_arima_forecast <- forecast(stl_arima_fit, h = length(methane_test_ts), xreg = methane_test_ts[,variable])

#accuracy assessment
stl_arima_accuracy <- accuracy(stl_arima_forecast$mean, methane_test_ts[,1])
  
  
  #####
  # Find the best variable
  #####
  
  result_list <- data.frame(
    Variable_colnum = paste(variable, collapse = ","),
    MAPE = stl_arima_accuracy["Variable Col Num", "MAPE"]
  )
  
  result <- append(result, list(result_list))
  
  cat("Variables:", variable, "\n")
  print(stl_arima_accuracy)

}

rmse_values <- sapply(result, function(x) x$MAPE)
best_index <- which.min(rmse_values)
best_result <- result[[best_index]]

print("The best combination is: \n")
print(best_result)

```










```{r}

SSES <- es(methane_train_ts[,1],model="ZZZ",h=35,holdout=FALSE,xreg=methane_train_ts[,-1])

SSES_for <- forecast(SSES, h = 35, newdata = methane_test_ts[,-1])

forecast_SSES_accuracy <- accuracy(SSES_for$mean, methane_test_ts[,1])

plot(SSES_for)

print(forecast_NN_accuracy)

```























### A template for looping

```{r}

variables <- list(c(2),c(2,3),c(2,4),c(2,5),c(2,3,4),c(2,3,5),c(2,4,5),c(2,3,4,5),c(3),c(3,4),c(3,5),c(3,4,5),c(4),c(4,5),c(5))

variables <- list(c(2),c(3),c(4),c(5))

result <- list()

for(variable in variables){

  
  
  
  #####
  # Find the best variable
  #####
  
  result_list <- data.frame(Variable_colnum = variable, RMSE = tbats_accuracy[,"MAPE"])
  
  result <- append(result,list(result_list))
  
  cat(variable,":\n")
  
  print(tbats_accuracy)

}

rmse_values <- sapply(result, function(x) x$RMSE)

best_index <- which.min(rmse_values)

best_result <- result[[best_index]]

print("The best combination is: \n")
print(best_result)

```










```{r}

SSES <- es(methane_train_ts[,1],model="ZZZ",h=35,holdout=FALSE,xreg=methane_train_ts[,-1])

SSES_for <- forecast(SSES, h = 35, newdata = methane_test_ts[,-1])

forecast_SSES_accuracy <- accuracy(SSES_for$mean, methane_test_ts[,1])

plot(SSES_for)

print(forecast_NN_accuracy)

```


