---
title: "Forecasting_Jingze"
output: 
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

Importing library

```{r}
library(forecast)
library(ggplot2)
library(kableExtra)

set.seed(797)
```


Loading dataset 

```{r}
methane_train <- read.csv("./Data/Processed/methane_training.csv")
methane_test <- read.csv("./Data/Processed/methane_test.csv")
```

Creating time series

```{r}
methane_train_ts <- ts(methane_train$average, start = c(1983, 7), frequency = 12)
methane_test_ts  <- ts(methane_test$average,  start = c(2022, 1), frequency = 12)

#multi-seasonal 
methane_train_msts <- msts(methane_train$average, seasonal.periods = c(4, 12), start = c(1983, 7))
```

STL+ETS forecast

```{r}
#fit STL with ETS
stl_ets_fit <- stlm(methane_train_ts, s.window = "periodic", method = "ets")
print(stl_ets_fit$model)

#forecasting test data
stl_ets_forecast <- forecast(stl_ets_fit, h = length(methane_test_ts))

#accuracy assessment
stl_ets_accuracy <- accuracy(stl_ets_forecast$mean, methane_test_ts)

#visualization
plot(stl_ets_forecast)
```

TBATS forecast

```{r}
#fit TBATS
tbats_fit <- tbats(methane_train_msts)
print(tbats_fit)
checkresiduals(tbats_fit)

#forecasting test data
tbats_forecast <- forecast(tbats_fit, h = length(methane_test_ts))

#accuracy assessment
tbats_accuracy <- accuracy(tbats_forecast$mean, methane_test_ts)

#visualization
plot(tbats_forecast)
```


Performance comparison

```{r}
forecast_performance_Jingze <- data.frame(rbind(stl_ets_accuracy,
                                                tbats_accuracy))

rownames(forecast_performance_Jingze) <- c("STL + ETS", "TBATS")

#comparison table
kable(forecast_performance_Jingze,
      caption = "Forecast Accuracy Comparison",
      digits = 3,
      booktabs = TRUE)
```

