---
title: "Data Wrangling and Visualization"
output: pdf
author: Jingze Dai & Rachael Stephan
editor_options: 
  chunk_output_type: console
---

```{r chunks, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r libraries}
#retrieve libraries
library(here)
library(ggplot2)
library(forecast)
library(cowplot)
library(Kendall)
library(tseries)
library(tidyverse)
library(lubridate)
```

```{r theme, include=FALSE}
#create plot theme
mytheme <- theme_bw(base_size = 10)+
  theme(axis.title = element_text(size = 10, hjust = 0.5),
        plot.title.position = "panel",
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.25),
        plot.caption = element_text(hjust = 0),
        legend.box = "vertical",
        legend.location = "plot",
        axis.gridlines = element_line(color = "grey", linewidth = 0.25),
        axis.ticks = element_line(color = "black", linewidth = 0.5),
        axis.grid = element_blank())

#set plot theme
theme_set(mytheme)
```

```{r}
#upload raw data and process it
temp_anomaly <- read.csv("./Data/Raw/temperature_anomaly.csv", 
                         skip = 4, 
                         header = TRUE) %>%
  mutate(Date = ym(Date))
```

```{r}
#process data out into relevant types of groupings
#by year
temp_anomaly_yearly <- temp_anomaly %>%
  mutate(year = year(Date)) %>%
  group_by(year) %>%
  summarize(year_anomaly = mean(Anomaly))

#subset by methane training years (1983-2021) and test years (2022-2024)
temp_anomaly_train <- temp_anomaly %>%
  mutate(year = year(Date)) %>%
  filter(year >= 1983 & year <= 2021) %>%
  select(-year)

temp_anomaly_test <- temp_anomaly %>%
  mutate(year = year(Date)) %>%
  filter(year >= 2022 & year <= 2024)%>%
  select(-year)

temp_anomaly_yearly_train <- temp_anomaly_yearly %>%
  filter(year >= 1983 & year <= 2021)

temp_anomaly_yearly_test <- temp_anomaly_yearly %>%
  filter(year >= 2022 & year <= 2024)
```

```{r}
#write dataframes to csvs
#all data
write.csv(temp_anomaly, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_all.csv",
          row.names = FALSE)

#yearly all data
write.csv(temp_anomaly_yearly, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_year_all.csv",
          row.names = FALSE)

#data subsets
write.csv(temp_anomaly_yearly_test, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_year_test.csv",
          row.names = FALSE)

write.csv(temp_anomaly_yearly_train, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_year_train.csv",
          row.names = FALSE)

write.csv(temp_anomaly_test, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_test.csv",
          row.names = FALSE)

write.csv(temp_anomaly_train, 
          file = "./Data/Processed/Temp_Anomaly/temp_anomaly_train.csv",
          row.names = FALSE)

```

