---
title: "Data Wrangling and Visualization"
output: pdf
author: Jingze Dai & Rachael Stephan
editor_options: 
  chunk_output_type: console
---

```{r chunks, include=FALSE}
#set up chunk options
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), 
                      tidy=FALSE) 
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r libraries}
#retrieve libraries
library(here)
library(ggplot2)
library(forecast)
library(cowplot)
library(Kendall)
library(tseries)
library(lubridate)
```

```{r theme, include=FALSE}
#create plot theme
mytheme <- theme_bw(base_size = 10)+
  theme(axis.title = element_text(size = 10, hjust = 0.5),
        plot.title.position = "panel",
        panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.25),
        plot.caption = element_text(hjust = 0),
        legend.box = "vertical",
        legend.location = "plot",
        axis.gridlines = element_line(color = "grey", linewidth = 0.25),
        axis.ticks = element_line(color = "black", linewidth = 0.5),
        axis.grid = element_blank())

#set plot theme
theme_set(mytheme)
```

#Methane Data

```{r data_retrieval}
#retrieve column names
header <- read.csv("./Data/Raw/noaa_ch4_monthly.csv", skip = 45, header = FALSE)
header <- header[1, ]

#retrieve monthly data
methane <- read.csv("./Data/Raw/noaa_ch4_monthly.csv", skip = 47, header = FALSE)

#set column names
colnames(methane) <- header

#create date column
methane$date <- make_date(year = methane$year, month = methane$month, day = 1)

#check for missing data
sum(is.na(methane))

#summary of the dataset
summary(methane$average)
```

```{r}
#subset data into training (1983-2021) and test data (2022-2024)
methane_training <- subset(methane, year <= 2021)
methane_test <- subset(methane, year >= 2022)

#save data to processed folder
write.csv(methane, 
          file = "./Data/Processed/methane_all.csv",
          row.names=FALSE)

write.csv(methane_test, 
          file = "./Data/Processed/methane_test.csv",
          row.names=FALSE)

write.csv(methane_training, 
          file = "./Data/Processed/methane_training.csv",
          row.names=FALSE)
```
 
```{r ts_set}
#create timeseries object of 
methane_train_ts <-ts(methane_training$average, 
                start = c(1983,7), 
                end = c(2021, 12), 
                frequency = 12)

#plot timeseries
autoplot(methane_train_ts)+
  labs(title = "Globally Averaged Atmospheric Methane Concentrations from 1983 to 2021",
       y = "Methane (ppb)")
```

# Temperature Data

```{r data_retrieval}

#retrieve monthly data
tempanom <- read.csv("./Data/Raw/temperature_anomaly.csv", skip = 5, header = FALSE) %>%
  mutate(V1 = ym(V1))

#set column names
colnames(tempanom) <- c("date", "temp_anomaly")

#check for missing data
sum(is.na(tempanom))

#summary of the dataset
summary(tempanom$temp_anomaly)
```

```{r}
#subset data into training (1983-2021) and test data (2022-2024)
tempanom_training <- subset(tempanom, year(date) <= 2021 & year(date) >= 1983)
tempanom_test <- subset(tempanom, year(date) >= 2022 & date <= max(methane$date))

#save data to processed folder
write.csv(tempanom, 
          file = "./Data/Processed/tempanom_all.csv",
          row.names=FALSE)

write.csv(tempanom_test, 
          file = "./Data/Processed/tempanom_test.csv",
          row.names=FALSE)

write.csv(tempanom_training, 
          file = "./Data/Processed/tempanom_training.csv",
          row.names=FALSE)
```

```{r}
#process data out into relevant types of groupings
#by year
temp_anomaly_yearly <- tempanom %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(year_anomaly = mean(temp_anomaly))

temp_anomaly_yearly_train <- temp_anomaly_yearly %>%
  filter(year >= 1983 & year <= 2021)

temp_anomaly_yearly_test <- temp_anomaly_yearly %>%
  filter(year >= 2022 & year <= 2024)

write.csv(temp_anomaly_yearly, 
          file = "./Data/Processed/tempanom_year_all.csv",
          row.names = FALSE)

write.csv(temp_anomaly_yearly_test, 
          file = "./Data/Processed/tempanom_year_test.csv",
          row.names = FALSE)

write.csv(temp_anomaly_yearly_train, 
          file = "./Data/Processed/tempanom_year_train.csv",
          row.names = FALSE)
```

